i18n-util/src/LocaleUtil.js, i18n-util/src/UrlUtil.js, i18n-util/test/spec/LocaleUtil_spec.js, i18n-util/test/spec/UrlUtil_spec.js, i18n-util/yarn.lock
Previous changes to 'i18n-util' code were made to enable a `lang-locale` identifier in URLs originating from Okta Admin portal for Classic/V1 pages (e.g., `https://help.okta.com/en-us/Content/index-admin.htm`).
However, after making this change, many QA tests started failing, with flaky results.
Reverting those changes for now, until we find the reason for the failures and can then apply a comprehensive fix.
=> Rolling back changes to  'i18n-util' code

robots.txt
Removing the entries for disallowing '/en/' and '/end-user/'.
These directories contain HTML files that have noindex-nofollow metadata
set in the headers, we want that data exposed to crawlers.
Likewise, removing the disallow entry for '/preview/', that directory no longer exists.
Also, adding a disallow entry for the '/tests/' dir, crawlers don't
need to review our Cypress tests.
=> Editing robots.txt file

tests/cypress/integration/pdv_hoc_site_spec.js
We had a failure in our post-deploy testing that wasn't caught by pre-deploy testing. Closing that gap. 
Adding tests for checking tab functionality on release notes pages in OIE and Classic:
- Ensure that the `defer` attributes have been removed where necessary
- Check number of tabs is as expected
- Check that each tab becomes active on click
=> Adding Cypress tests to ensure tab functionality works

ci-scripts/commit-artifact.sh
Changes:
`PUBLISH_DESTINATION` and `BUILT_ARTIFACT` are passed in by `info-dev` bacon task. `BUILT_ARTIFACT` - url to the built artifact, that we want to publish. `PUBLISH_DESTINATION` - destination folder (asa, oie, e.t.c.).
For the branch name we use destination folder, which is a product name, and current timestamp to not accidentally push changes into existing branch.
Script performs next actions:
- `wget` - downloads zip from server
- `tar -xf` - extracts zip to the specified location
- `git commands` - stages changes and pushes them to the github
for the first iteration user will have to find branch on github.com/okta-help and create PR manually
Jira:
[OKTA-542673](https://oktainc.atlassian.net/browse/OKTA-542673)
Reviewer:
@paulwallace-okta
=> Commits built artifact to okta-help

ci-scripts/request-translation.sh
- adds task on bacon with product name parameter (asa, oie, oce, oag, fw, eu) which will create a branch for translation
- copies resources from en-us folder to ja-jp. Resource paths:
- Data
- Content/Resources
- Resources
- Skins
- Excludes Tocs, which has js files for translation
- when task is completed, sends notification to publish channel. (maybe will rename channel to `infodev-notifications` or something)
There are two ways of triggering task:
1. is through bacon tasks https://bacon-go.aue1e.saasure.net/tasks/CI_DOC_TOOLS_REQUEST_TRANSLATION, just run task and select corresponding target
2. is to run it via slack: `@Baconbot run task CI_DOC_TOOLS_REQUEST_TRANSLATION`
Will show both options on stand up
- [OKTA-549554](https://oktainc.atlassian.net/browse/OKTA-549554)
- …
=> Script for translation topic branches

ci-scripts/request-translation.sh
- Copies Sitemap.xml from `en-us` to `ja-jp` folder
reference form test translation PR:
https://github.com/okta/okta-help/pull/601/files#diff-490e144a02b1a9a35726adf8a6ed3b7c59bf03f2686e93e4bcdc64b78d9b83d0L1
- [OKTA-553877](https://oktainc.atlassian.net/browse/OKTA-553877)
=> Copies sitemap to the ja-jp folder

ci-scripts/commit-artifact.sh
It appears on linux job we run job with higher user privileges. That has a side effect during unpacking files from tar, files in output have more relaxed permissions (`rw-r-r` is what we usually have and `rw-rw-r` is what we get after unpacking files). As result almost every file is tracked as modified with no actual change in the content.
On unpacking tar usually applies current user mask to files, which makes result permissions to be `rw-r-r` even if file has higher permissions in archive. However for the root user it ignores `umask`, flag `--no-same-permissions` forces it to apply the mask.
After the fix, generated PR has only files with modified content:
https://github.com/okta/okta-help/pull/621/files
- [OKTA-553185](https://oktainc.atlassian.net/browse/OKTA-553185)
- …
=> Fixes ci permissions on files extraction

ja-jp/Content/Topics/ReleaseNotes/early-access.htm, ja-jp/Content/Topics/ReleaseNotes/mobile-release-status.htm, ja-jp/Content/Topics/ReleaseNotes/okta-verify-release-notes.htm, ja-jp/Content/Topics/ReleaseNotes/preview.htm, ja-jp/Content/Topics/ReleaseNotes/production.htm, ja-jp/Content/Topics/ReleaseNotes/release-faq.htm, scripts/en2ja.json, scripts/translation_postprocessing.py, wf/ja-jp/Content/Topics/ReleaseNotes/Workflows/preview.htm, wf/ja-jp/Content/Topics/ReleaseNotes/Workflows/production.htm, wf/ja-jp/Content/Topics/Workflows/build/create-table.htm
The sitemaps (EN and JA) are in XML format. Each publication has four XML files total.
We want to apply our string replacement script to the JA sitemaps (copied over from EN). This change adds a check for XML file extension, enabling parsing of these files.
Our string replacement script already includes pairs for the publication base links. We're applying that to the sitemaps.
Added bonus: The `Data/HelpSystem.xml` file includes a Support path, our string replacer adds the JA lang query string to this URL.
Additionally, changing absolute URLs to relative paths. The release notes files here are static, we don't build these in Flare.
=> Update translation post-processing script to handle sitemaps

tests/cypress/integration/locale_selector_spec.js
Took main idea from here https://www.cypress.io/blog/2018/02/05/when-can-the-test-start/
We need to wait for event listener to be set for the change language button, only after that we can proceed with the test. That's required only for locale switcher tests.
- [OKTA-551747](https://oktainc.atlassian.net/browse/OKTA-551747)
=> Fix flaky cypress test

ci-scripts/commit-artifact.sh
In addition to existing flow, we also running `git fetch origin topic_branch`:
- failure: there is no topic_branch on remote, so we create one
- success: there is a topic_branch and we fetched it to local, we can now check it out
The rest remains unchanged. For incremental changes we will have same commit message, at least for now.
- [OKTA-555235](https://oktainc.atlassian.net/browse/OKTA-555235)
=> Re-uses branch if it exists

scripts/en2ja.json, scripts/test_translation_postprocessing.py, scripts/translation_postprocessing.py
- updates both `lang="en-us"` `xml:lang="en-us"` to `ja-jp`
- removes some trailing whitespaces (VS Code does this automatically)
- [OKTA-561129](https://oktainc.atlassian.net/browse/OKTA-561129)
=> Updates language attribute to ja-jp

ci-scripts/request-translation.sh
- Moves release notes folder out of `Topics` for OCE and OIE targets(seems like only those two have release notes inside of Topics).
- Fixes `rsync`, which didn't sync path with sub folders correctly.
- [OKTA-563585](https://oktainc.atlassian.net/browse/OKTA-563585)
=> Move ReleaseNotes for oce oie

ci-scripts/commit-artifact.sh
- creates folder for the output path, otherwise publish script fails for new location
- [OKTA-567227](https://oktainc.atlassian.net/browse/OKTA-567227)
=> Create path for publishing to a new location

ci-scripts/commit-artifact.sh
- accepts url to file with list of built targets along with destination locations. "old" single target build still works for backward compatibility, while I'm completing changes on `info-dev` side
- [OKTA-571529](https://oktainc.atlassian.net/browse/OKTA-571529)
=> Applies a list of built targets

tests/cypress/integration/locale_selector_spec.js
Heh, I've overlooked something completely.  I figured out that we have issue with madcap initialization when page loads and we start test too early. So we have `visitAndWaitForInitialize` to start test when madcap is good to go:
```
(1) visitAndWaitForInitialize('en-us/Content/index.htm')
(2) cy.switchLocale('Change language', '日本語 (日本)‎')
(3) cy.url().should('include', 'ja-jp/Content/index.htm')
(4) cy.switchLocale('言語を変更', 'English (United States)')
(5) cy.url().should('include', 'en-us/Content/index.htm')
```
But after `cy.switchLocale('Change language', '日本語 (日本)‎')` call, browser will load another page and we don't wait for its initialization.
Before the first fix test was failing on line (2), now it's failing on line (4) since new page is loaded and we just click on the locale …
=> Wait for madcap initialization on new page

ci-scripts/request-translation.sh
`rsync` is no longer available on our build dockers 🤦 that tool allowed to copy all files and ignore `Data\Tocs`, no easy way to achieve the same behaviour.
Instead we'll copy all resource folders and then use git to revert Tocs files.
translation PR for a test topic branch:
https://github.com/okta/okta-help/pull/925/files
[OKTA-587123](https://oktainc.atlassian.net/browse/OKTA-587123)
=> copy en resource to ja-jp

ci-scripts/request-translation-ll.sh
- When syncing en-us contents from gh-pages to the translation branch, we skip ReleaseNotes. For the Netlify project, we need to skip relesenotes (all lowercase)
[OKTA-611207](https://oktainc.atlassian.net/browse/OKTA-611207)
=> Excludes release notes for lowercase path

.bacon.yml, ci-scripts/cypress.sh
It was a surprisingly challenging task. There are two approaches for it:
- Duplicate cypress test in bacon task. Run `yarn install` and `yarn cy:run`.
- Wait for GitHub workflow action from the bacon task.
For 1) I could not get cypress installed correctly on bacon, we also needed a different `node` version, because the default is incompatible with our setup. And we would also run tests two times, the first one from github and the second one from bacon.
2) is a bit exotic 😄 We're querying status from GH, depending on when we start the bacon task, we may already have test results in GH. Also, our GH action is configured for PRs only and bacon shows test for every commit even if there is no PR (for this case test should fail)
Api can be found here …
=> Em okta 627781 add tests suite

scripts/en2ja.json
We have several tickets generated from LQA feedback, recommending we update our Microsoft links for JA.
Helpfully, Microsoft has i18nized their content, and publishes in many languages.
They also maintain several subdomains, to which we link.
Adding a string replacement pair to update the links to Microsoft resources for JA.
=> Adding l10n string replacement pair

ci-scripts/commit-artifact.sh
- clears `en-us` folder for prod builds before copying built artifact to it.
- betas targets don't have `en-us` path, the script won't do anything in that case
[OKTA-649406](https://oktainc.atlassian.net/browse/OKTA-649406)
=> clears en-us folder for prod builds

_redirects
Here are broken links per ja-jp product:
- OCE https://preview-1623--extraordinary-horse-71260e.netlify.app/ja-jp/not-found.html
- ASA https://preview-1623--extraordinary-horse-71260e.netlify.app/asa/ja-jp/not-found.html
- OAG https://preview-1623--extraordinary-horse-71260e.netlify.app/oag/ja-jp/not-found.html
- EU https://preview-1623--extraordinary-horse-71260e.netlify.app/eu/ja-jp/not-found.html
- OIE https://preview-1623--extraordinary-horse-71260e.netlify.app/oie/ja-jp/not-found.html
- WF https://preview-1623--extraordinary-horse-71260e.netlify.app/wf/ja-jp/not-found.html
[OKTA-662454](https://oktainc.atlassian.net/browse/OKTA-662454)
=> Adds redirect for ja-jp 404 page

ci-scripts/cypress.sh, cypress.json, tests/cypress/support/commands.js
- Hides a drop-down menu, when it's no longer needed. Just noticed on the local run that drop down is not automatically closed when test continues to the next steps <img width="758" alt="image" src="https://github.com/okta/okta-help/assets/4158731/10a53a79-879b-4e88-9dcb-7e671e78753b">
- Changes viewport configuration so the test will pass, but we have a bug in UI when Coveo search bar is not visible: https://oktainc.atlassian.net/browse/OKTA-667840
- Uploads screenshots from failed tests, so it will be easier to investigate issues in the future.
[OKTA-664039](https://oktainc.atlassian.net/browse/OKTA-664039)
=> fixes cypress tests

ci-scripts/receive-translation-ll.sh, scripts/translation_postprocessing.py
- checks out en-us sitemap from long-lived translation branch
- reads all file names from sitemap
- iterates through ja-jp topics and deletes those that are not in a sitemap. Exceptions are release notes and files not in the topics folder.
Here is the PR from the receiving job https://github.com/okta/okta-help/pull/1733 - look at ja-jp topics folder.
- [OKTA-671306](https://oktainc.atlassian.net/browse/OKTA-671306)
=> Syncs translated folder with en-us

index.html, okta_help.htm
Titles should render "Okta Docs" in apps that render titles from embedded links, such as Jira and Confluence.
Also, revising the meta http-equiv syntax, the content attr was non-standard format, now formatted correctly.
=> OKTA-696583: H.O.C. index page titles

ci-scripts/request-translation-ll.sh
- Restores `Search*.js` files from LL translation branch, so that when resources from en-us are copied to ja-jp folder files required for ja-jp search remain untouched.
- [OKTA-755603](https://oktainc.atlassian.net/browse/OKTA-755603)
=> Em okta 755603

ci-scripts/receive-translation-ll.sh, ci-scripts/request-translation-ll.sh
- Starts i18n sync after the request translation script is done.
[Dry run](https://bacon-go.aue1e.saasure.net/tasks/I18N_SYNC_TRANSLATIONS?taskId=d77628757ecf445d919898bb414d6aa7) on i18n sync triggered from [test bacon task](https://bacon-go.aue1e.saasure.net/tasks/CI_DOC_TOOLS_TEST?taskId=a140584853b64895b6044515f3f59b9a)
- [OKTA-821634](https://oktainc.atlassian.net/browse/OKTA-821634)
=> Starts i18n sync task
