.github/CODEOWNERS
https://oktainc.atlassian.net/browse/OKTA-480430
=> OKTA-480430: Place a codeowners guard on i18n-utils files

googleb8832921006355d2.html
Used for Google Search Console.
I need to verify the ownership before seeing any index and data.
=> Add Google verification file for Hor-kan

en-us/Content/Topics/ReleaseNotes/preview.htm, oie/en-us/Content/Topics/ReleaseNotes/preview-oie.htm, oie/en-us/Content/Topics/ReleaseNotes/production-oie.htm
=> Update RN for 2022.08.2 HF

.eslintrc, .github/workflows/run-cypress-tests.yml, .npmrc_, .yarnrc_, cypress.json, package.json, tests/README.md, tests/cypress/integration/aliases_spec.js, tests/cypress/integration/browser_langs_spec.js, tests/cypress/integration/hoc_homepage_spec.js, tests/cypress/integration/locale_selector_spec.js, tests/cypress/integration/okta_asa_spec.js, tests/cypress/integration/okta_classic.relnotes_spec.js, tests/cypress/integration/okta_classic_spec.js, tests/cypress/integration/okta_enduser_spec.js, tests/cypress/integration/okta_oag_spec.js, tests/cypress/integration/okta_oie.relnotes_spec.js, tests/cypress/integration/okta_oie_spec.js, tests/cypress/integration/okta_wf_spec.js, tests/cypress/support/commands.js, tests/cypress/support/index.js, yarn.lock
- Adds modules required for eslint, adds gh action to run lint checks and also fixes all errors highlighted by those checks
- Adds gh action to upload screen shots from failed build
- Hopefully fixes flaky tests related to locale switching
in failed job there is an artifact section: https://github.com/okta/okta-help/actions/runs/3440772850
where in zip file we can get more information about the failure
- [OKTA-549553](https://oktainc.atlassian.net/browse/OKTA-549553)
=> Okta 549553 run tests on bacon

ci-scripts/request-translation.sh
- Changes slack channel to `infodev-notifications`
* [OKTA-551742](https://oktainc.atlassian.net/browse/OKTA-551742)
=> Changes slack channel

tests/cypress/integration/sitemap_spec.js
- loads sitemap, then reads ~20 urls from file and gets resource.
- 
- [OKTA-555977](https://oktainc.atlassian.net/browse/OKTA-555977)
=> Verifies 20 urls from every en sitemap

en-us/Content/Topics/Settings/Version_Histories/Ver_History_Browser_Plugin.htm
=> Updates OCE with plugin support update

scripts/test_translation_postprocessing.py, scripts/translation_postprocessing.py
- Uses target names to run post processing. I'm still using hardcoded `ja-jp` as we don't have any other language.
- [OKTA-563582](https://oktainc.atlassian.net/browse/OKTA-563582)
=> Uses targets in post translate step

scripts/translation_postprocessing.py
When we request translation from bacon task, we have to "hide" release notes from XTM. That's achieved by moving ReleseNotes up to a `en-us` folder - for example new location for asa would be `asa/en-us/ReleaseNotes`. 
When we process translation we also need to move ReleaseNotes folder to its original location. When it's time to merge translation back to gh-pages branch we should not see any changes in release notes folder.
- [OKTA-563586](https://oktainc.atlassian.net/browse/OKTA-563586)
=> Restores release notes to original location

.github/workflows/run-cypress-tests.yml, tests/cypress/integration/sitemap_spec.js
https://oktainc.atlassian.net/browse/OKTA-565662
Ironically, the GH Actions / Cypress tests are quite flaky right now. You can try running this locally.
=> Refactoring sitemap tests

package.json, yarn.lock
The 'glob-parent@5.1.2' package has a vuln. Applying a resolution for that package above @6.0.1 (per CVE).
=> Adding resolutions to package.json

oie/en-us/Content/Topics/ReleaseNotes/preview-oie.htm, oie/en-us/Content/Topics/ReleaseNotes/production-oie.htm
=> Updates OIE RN for 2023.01.1

ci-scripts/commit-artifact.sh
- unzips artifact
* [OKTA-578315](https://oktainc.atlassian.net/browse/OKTA-578315)
=> Unzips artifact

ci-scripts/receive-translation-ll.sh, ci-scripts/request-translation-ll.sh, ci-scripts/setup-translation-ll.sh, scripts/translation_postprocessing.py
Implementing jobs to push updates for `en-us` product to long lived translation branch and to get `ja-jp` translation back to `gh-pages`.
- [OKTA-585860](https://oktainc.atlassian.net/browse/OKTA-585860)
=> Adds translation tasks for LL branch

package.json, yarn.lock
- Resolves ramda to the latest 0.28.0 which does not have voln
- [OKTA-550243](https://oktainc.atlassian.net/browse/OKTA-550243)
- @hor-kanchan-okta
=> Updates ramda to the latest

ci-scripts/setup-translation-ll.sh
Updates long lived branch to `docs_translations_gh_{product}`
https://oktainc.atlassian.net/browse/OKTA-594860?focusedCommentId=3457812
- [OKTA-594860](https://oktainc.atlassian.net/browse/OKTA-594860)
=> Updates long lived branch name

ci-scripts/setup-translation-ll.sh
Updates long lived branch to `docs_translations_gh_{product}`
https://oktainc.atlassian.net/browse/OKTA-594860?focusedCommentId=3457812
- [OKTA-594860](https://oktainc.atlassian.net/browse/OKTA-594860)
=> sets long lived branch name

ci-scripts/setup-translation-ll.sh
- remove debugging code
- none
=> removes test translation branch

en-us/Content/Topics/ReleaseNotes/preview.htm, en-us/Content/Topics/ReleaseNotes/production.htm, oie/en-us/Content/Topics/ReleaseNotes/preview-oie.htm, oie/en-us/Content/Topics/ReleaseNotes/production-oie.htm
=> Update OIE RN for HF

ci-scripts/resend-translation-ll.sh
- adds script which will update en-us htm files for the project. We will use it from bacon task https://bacon-go.aue1e.saasure.net/tasks/CI_DOC_TOOLS_RESEND_TRANSLATION_LL to request translation for all English files.
[OKTA-612851](https://oktainc.atlassian.net/browse/OKTA-612851)
=> change all en files for translation

wf/en-us/Content/Topics/Workflows/connector-reference/connector-reference.htm, wf/en-us/Content/Topics/Workflows/connector-reference/jamfproapi/jamfproapi.htm
@netlify /wf/en-us/content/topics/workflows/connector-reference/jamfproapi/jamfproapi
=> Fixing unresolved variable in WF

ci-scripts/receive-translation-ll.sh
- fixes typo in git command
- NA
=> fixes git command

ci-scripts/request-translation-ll.sh
- copies resources for the lowercase folder
- [OKTA-611207](https://oktainc.atlassian.net/browse/OKTA-611207)
=> copies resources for lowercase

ci-scripts/setup-translation-ll.sh
- for the migrated targets runs Netlify version of the request and receive the translation script
- [OKTA-620496](https://oktainc.atlassian.net/browse/OKTA-620496)
=> Updates translation requests for Netlify targets

asa/ja-jp/content/topics/releasenotes/advanced-server-access-release-notes.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2017.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2018.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2019.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2020.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2021.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2022.htm, ja-jp/content/topics/releasenotes/archive/oce-relnotes-2023.htm, ja-jp/content/topics/releasenotes/early-access.htm, ja-jp/content/topics/releasenotes/mobile-release-status.htm, ja-jp/content/topics/releasenotes/okta-relnotes.htm, ja-jp/content/topics/releasenotes/okta-verify-release-notes.htm, ja-jp/content/topics/releasenotes/preview.htm, ja-jp/content/topics/releasenotes/production.htm, ja-jp/content/topics/releasenotes/release-faq.htm, oie/ja-jp/content/topics/releasenotes/archive/oie-relnotes-2021.htm, oie/ja-jp/content/topics/releasenotes/archive/oie-relnotes-2022.htm, oie/ja-jp/content/topics/releasenotes/archive/oie-relnotes-2023.htm, oie/ja-jp/content/topics/releasenotes/early-access.htm, oie/ja-jp/content/topics/releasenotes/oie-ov-release-notes.htm, oie/ja-jp/content/topics/releasenotes/preview-oie.htm, oie/ja-jp/content/topics/releasenotes/production-oie.htm, wf/ja-jp/content/topics/workflows/releasenotes/archive/wf-relnotes-2020.htm, wf/ja-jp/content/topics/workflows/releasenotes/archive/wf-relnotes-2021.htm, wf/ja-jp/content/topics/workflows/releasenotes/archive/wf-relnotes-2022.htm, wf/ja-jp/content/topics/workflows/releasenotes/archive/wf-relnotes-2023.htm, wf/ja-jp/content/topics/workflows/releasenotes/workflows/preview.htm, wf/ja-jp/content/topics/workflows/releasenotes/workflows/production.htm, wf/ja-jp/content/topics/workflows/releasenotes/workflows/workflows-release-notes.htm, wf/ja-jp/content/topics/workflows/releasenotes/workflows/workflows-version-history.htm
Adds redirects for ja-jp release notes
=> Adds ja-jp release notes

ci-scripts/setup-translation-ll.sh
- adds EU to list of Netlify targets in translations script.
- [OKTA-633687](https://oktainc.atlassian.net/browse/OKTA-633687)
=> adds eu to netlify targets

ci-scripts/setup-translation-ll.sh
- Moves OAG to Netlify. Will send and receive translation to the branch related to master.
- [OKTA-639380](https://oktainc.atlassian.net/browse/OKTA-639380)
=> moves oag to netlify

netlify.toml
- adds origin header
[OKTA-640759](https://oktainc.atlassian.net/browse/OKTA-640759)
=> Adds origin header

ci-scripts/cypress.sh, ci-scripts/setup-translation-ll.sh
- adds WF to Netlify targets for translation
- [OKTA-638587](https://oktainc.atlassian.net/browse/OKTA-638587)
- @IanHakes-okta
=> Adds WF to netlify targets

en-us/content/index.htm
- uses lowercase paths on the landing page
- [OKTA-642831](https://oktainc.atlassian.net/browse/OKTA-642831)
=> fix urls for the landing page

ci-scripts/setup-translation-ll.sh
- updates translation for OIE and OCE to work off Netlify LL branches
- [OKTA-640697](https://oktainc.atlassian.net/browse/OKTA-640697)
=> switches OIE and OCE translation to Netlify

.circleci/config.yml, .github/workflows/run-cypress-tests.yml, package.json, yarn.lock
=> Adds CCI configuration

ci-scripts/setup-translation-ll.sh
- removes Netlify related logic
- [OKTA-646882](https://oktainc.atlassian.net/browse/OKTA-646882)
=> updates script

asa/ja-jp/content/topics/releasenotes/advanced-server-access-release-notes.htm, ja-jp/content/topics/releasenotes/preview.htm, ja-jp/content/topics/releasenotes/production.htm, oag/ja-jp/content/topics/releasenotes/oag/oag-release-notes.htm, oie/ja-jp/content/topics/releasenotes/preview-oie.htm, oie/ja-jp/content/topics/releasenotes/production-oie.htm, wf/ja-jp/content/topics/releasenotes/workflows/preview.htm, wf/ja-jp/content/topics/releasenotes/workflows/production.htm
* OIE production: https://preview-1537--extraordinary-horse-71260e.netlify.app/oie/ja-jp/content/topics/releasenotes/production-oie.htm
* OIE preview: https://preview-1537--extraordinary-horse-71260e.netlify.app/oie/ja-jp/content/topics/releasenotes/preview-oie.htm
* OCE production: https://preview-1537--extraordinary-horse-71260e.netlify.app/ja-jp/content/topics/releasenotes/production.htm
* OCE preview: https://preview-1537--extraordinary-horse-71260e.netlify.app/ja-jp/content/topics/releasenotes/preview.htm
* WF production: https://preview-1537--extraordinary-horse-71260e.netlify.app/wf/ja-jp/content/topics/releasenotes/workflows/production.htm
* WF preview: https://preview-1537--extraordinary-horse-71260e.netlify.app/wf/ja-jp/content/topics/releasenotes/workflows/preview.htm
* OAG: …
=> Adding JA relnotes survey

wf/en-us/content/topics/releasenotes/workflows/production.htm
Need to do it fast for the update. 
Regular build will have the fix when the build is done.
=> Artisanal fix for Hot-fix release notes

ci-scripts/receive-translation-ll.sh
- Uses generated GH token for PR creation
- [OKTA-708212](https://oktainc.atlassian.net/browse/OKTA-708212)
=> Switches to generated gh token

ci-scripts/receive-translation-ll.sh
- switches to signed commits by bacon bot
- [OKTA-712252](https://oktainc.atlassian.net/browse/OKTA-712252)
=> Em okta 712252

ci-scripts/receive-translation-ll.sh
- imports gpg key and sings translation commit with it
- [OKTA-724380](https://oktainc.atlassian.net/browse/OKTA-724380)
=> sign commits from bacon task

.circleci/config.yml
- uses shallow checkout for speeding up CCI build
- [OKTA-735610](https://oktainc.atlassian.net/browse/OKTA-735610)
=> Uses shallow clone

ci-scripts/setup-translation-ll.sh
- adds ispm to the targets list in bacon job
- [OKTA-738391](https://oktainc.atlassian.net/browse/OKTA-738391)
=> Adds ispm translation

ci-scripts/resend-translation-ll.sh, scripts/translation_modify_files.py
- syncs scripts from master branch (we haven't used this script for ages)
- adds ispm target and also allows any new target
- [OKTA-738391](https://oktainc.atlassian.net/browse/OKTA-738391)
=> syncs scripts with master branch
